# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 05:54
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField()),
                ('link', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='blog/images/news-newsletter-newspaper-information-158651_5PJlC13.png', upload_to='blog/images')),
                ('thumbnail', models.ImageField(blank=True, default='blog/images/news-newsletter-newspaper-information-158651_5PJlC13.png', editable=False, null=True, upload_to='blog/images')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.diseases')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
