# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=511000)),
                ('image', models.ImageField(blank=True, upload_to='D:\\roajer\\hospitalevent\\hospitalevent\\site_media\\media')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event_cateogary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='EventSelect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_select', to='home.Event_Management')),
            ],
        ),
    ]
